# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "web-deploy"
  web-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      ftp_location: ftp.alexbartlett.com # Pass in required secrets.
      ftp_username: ${{ secrets.FTPLOGIN }}
      ftp_password: ${{ secrets.FTPKEY }} 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
      # Install the gems in the gemfile & install ncftp
      - name: Setup Environment.
        run: |
          bundle install
          sudo apt-get install -y ncftp
          
      # Sync files
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: $ftp_location
          username: $ftp_username
          password: $ftp_password
          server-dir: public_html/
          exclude: |
            **/.git*
            **/.git*/**
            **/.github*
            **/.vscode/**
            **/jekyll-blog*
      
      # Build the site
      - name: Build Site with Jekyll.
        run: |
          cd jekyll-blog
          JEKYLL_ENV=production bundle exec jekyll build
      
      # Looks kind of complicated but just uploads the content of _site folder to the ftp server. It does not upload the _site folder itself.
      - name: Upload site to FTP.
        env: 
          ftp_location: ftp.alexbartlett.com # Pass in required secrets.
          ftp_username: ${{ secrets.FTPLOGIN }}
          ftp_password: ${{ secrets.FTPKEY }} 
        run: |
          ncftpput -R -v -u "$ftp_username" -p "$ftp_password" $ftp_location /public_html/blog _site/* 